"""OAuth 2.0 PKCE flow orchestrator for Mixpanel.

Coordinates the full OAuth 2.0 Authorization Code + PKCE flow:
1. Dynamic Client Registration (via ``ensure_client_registered``)
2. PKCE challenge generation
3. Browser-based authorization
4. Local callback server to receive the authorization code
5. Token exchange
6. Token refresh

Example:
    ```python
    from mixpanel_headless._internal.auth.flow import OAuthFlow

    flow = OAuthFlow(region="us")
    tokens = flow.login()
    print(f"Access token: {tokens.access_token.get_secret_value()[:8]}...")
    ```
"""

from __future__ import annotations

import contextlib
import json
import queue
import secrets
import socket
import sys
import threading
import time
import webbrowser
from urllib.parse import parse_qs, urlencode

import httpx

from mixpanel_headless._internal.auth.callback_server import (
    CALLBACK_PORTS,
    CallbackResult,
    start_callback_server,
)
from mixpanel_headless._internal.auth.client_registration import (
    OAUTH_BASE_URLS,
    ensure_client_registered,
)
from mixpanel_headless._internal.auth.pkce import PkceChallenge
from mixpanel_headless._internal.auth.storage import OAuthStorage
from mixpanel_headless._internal.auth.token import OAuthTokens
from mixpanel_headless.exceptions import OAuthError

# Token-endpoint response keys whose values are structurally non-secret
# RFC 6749 §5.1 metadata. ONLY these survive redaction (and only when the
# value is a primitive) — every OTHER value in a malformed 200 token payload
# is replaced with "<redacted>", whatever its key: pair-B review (ARB-B
# F-B2/E-1) probe-confirmed that a deny-list over canonical token keys leaks
# nested envelopes ({"result": {"access_token": ...}}), list values,
# non-canonical credential keys (client_secret) and case-variant keys
# (Access_Token). See _post_token_request's Security note.
_SAFE_TOKEN_DETAIL_KEYS: frozenset[str] = frozenset(
    {"token_type", "expires_in", "scope", "error", "error_description"}
)

# Rendering for non-object 200 JSON token bodies in error details: the VALUE
# itself can be the credential (an IdP returning the bare token as a JSON
# string), so it never renders verbatim (ARB-B F-B3; byte-identical constant
# in the TS twin, oauth-http.ts).
_NON_OBJECT_BODY_PLACEHOLDER = "<redacted non-object body>"


def _redact_token_payload(data: object) -> str:
    """Render a malformed 200 token payload safely for OAuthError details.

    Allowlist redaction (ARB-B hardening of the FIX-2 deny-list): every
    field NAME stays visible for diagnosis, but only the values of
    ``_SAFE_TOKEN_DETAIL_KEYS`` survive — and only when they are primitives
    (``str`` / ``int`` / ``float`` / ``bool`` / ``None``). Every other
    value renders as ``"<redacted>"`` regardless of nesting, and a
    non-object body renders as ``_NON_OBJECT_BODY_PLACEHOLDER``, so no
    value channel can carry bearer material into serialized error details.

    Args:
        data: The parsed 200 token-endpoint JSON body (any JSON value —
            ``response.json()`` is not limited to objects).

    Returns:
        The ``str()`` rendering of the redacted mapping (byte-matching the
        TS twin's ``pythonStr``), or the fixed placeholder for non-object
        bodies.

    Example:
        ```python
        _redact_token_payload({"access_token": "SECRET", "scope": "projects"})
        # "{'access_token': '<redacted>', 'scope': 'projects'}"
        ```
    """
    if not isinstance(data, dict):
        return _NON_OBJECT_BODY_PLACEHOLDER
    return str(
        {
            k: (
                v
                if k in _SAFE_TOKEN_DETAIL_KEYS
                and (v is None or isinstance(v, (str, int, float)))
                else "<redacted>"
            )
            for k, v in data.items()
        }
    )


def _parse_pasted_redirect(line: str, *, expected_state: str) -> CallbackResult:
    """Parse a pasted OAuth redirect URL or query string into a CallbackResult.

    Used by the ``--no-browser`` paste fallback in :meth:`OAuthFlow.login`.
    Mixpanel's ``redirect_uri_allowed`` (per ``webapp/oauth/models.py``)
    permits any ``http://localhost:<port>/`` URL, so the OAuth provider
    successfully issues a redirect even when no local server is listening
    — the user copies the URL from the failed-to-load tab in their browser
    and pastes it back to the CLI process that's still holding the in-memory
    PKCE verifier.

    Accepts (whitespace-trimmed):
        - Full redirect URL: ``http://localhost:19284/callback?code=ABC&state=XYZ``
        - Query string with leading ``?``: ``?code=ABC&state=XYZ``
        - Query string only: ``code=ABC&state=XYZ``

    Validates that the pasted ``state`` matches ``expected_state`` (CSRF
    protection — without this check a hostile party could trick the user
    into pasting an attacker-supplied code).

    Args:
        line: The text the user pasted on stdin.
        expected_state: The ``state`` value generated by this login session.

    Returns:
        :class:`CallbackResult` with the extracted ``code`` and ``state``.

    Raises:
        OAuthError: The paste was empty / unparseable, contained an
            ``error=`` parameter from the OAuth provider, was missing
            ``code`` or ``state``, or the state did not match.
    """
    line = line.strip()
    if not line:
        raise OAuthError(
            "Empty paste — expected the redirect URL or `code=...&state=...`.",
            code="OAUTH_PASTE_ERROR",
        )
    # Strip everything up to and including the first `?` so both the full
    # URL form and the bare query-string form parse the same way.
    query_part = line.split("?", 1)[1] if "?" in line else line
    params = parse_qs(query_part)
    if "error" in params:
        err = params["error"][0]
        desc = params.get("error_description", [""])[0]
        raise OAuthError(
            f"OAuth provider returned an error: {err}" + (f" — {desc}" if desc else ""),
            code="OAUTH_AUTH_DENIED",
        )
    code_list = params.get("code", [])
    state_list = params.get("state", [])
    if not code_list or not state_list:
        raise OAuthError(
            "Pasted text is missing `code` or `state` parameters. "
            "Paste the full redirect URL (e.g., http://localhost:.../callback?code=...&state=...).",
            code="OAUTH_PASTE_ERROR",
        )
    code = code_list[0]
    state = state_list[0]
    if state != expected_state:
        raise OAuthError(
            "State mismatch — the pasted text does not belong to this login session.",
            code="OAUTH_STATE_MISMATCH",
        )
    return CallbackResult(code=code, state=state)


class OAuthFlow:
    """Orchestrator for the OAuth 2.0 Authorization Code + PKCE flow.

    Manages the full interactive login sequence: client registration,
    PKCE challenge generation, browser authorization, callback handling,
    and token exchange. Also supports token refresh.

    Attributes:
        region: Mixpanel data residency region (``us``, ``eu``, or ``in``).

    Example:
        ```python
        flow = OAuthFlow(region="us")
        tokens = flow.login(project_id="12345")
        # Later, refresh tokens:
        new_tokens = flow.refresh_tokens(tokens, client_id="my-client")
        ```
    """

    def __init__(
        self,
        region: str = "us",
        *,
        storage: OAuthStorage | None = None,
        http_client: httpx.Client | None = None,
    ) -> None:
        """Initialize the OAuth flow orchestrator.

        Args:
            region: Mixpanel data residency region (default ``"us"``).
                Must be one of ``"us"``, ``"eu"``, or ``"in"``.
            storage: OAuthStorage instance for caching tokens and client info.
                Uses the default storage location if not provided.
            http_client: httpx.Client for making HTTP requests. A default
                client is created if not provided.

        Example:
            ```python
            flow = OAuthFlow(region="eu")
            flow = OAuthFlow(region="us", storage=OAuthStorage(Path("/tmp")))
            ```
        """
        if region not in OAUTH_BASE_URLS:
            raise OAuthError(
                f"Unknown region: {region!r}. Must be one of: "
                f"{', '.join(sorted(OAUTH_BASE_URLS.keys()))}",
                code="OAUTH_CONFIG_ERROR",
            )
        self._region = region
        self._storage = storage or OAuthStorage()
        self._http_client = http_client or httpx.Client()
        self._base_url = OAUTH_BASE_URLS[region]

    @property
    def region(self) -> str:
        """Mixpanel data residency region.

        Returns:
            The region string (``us``, ``eu``, or ``in``).
        """
        return self._region

    def get_valid_token(self, region: str) -> str:
        """Return a valid access token, refreshing if expired.

        Loads tokens from storage, checks if expired, auto-refreshes if
        needed, persists refreshed tokens, and returns the access token string.

        Args:
            region: Mixpanel data residency region (``us``, ``eu``, or ``in``).

        Returns:
            A valid OAuth access token string.

        Raises:
            OAuthError: If no tokens exist (``OAUTH_TOKEN_ERROR``),
                no client info exists for refresh (``OAUTH_REFRESH_ERROR``),
                or the refresh request fails (``OAUTH_REFRESH_ERROR``).

        Example:
            ```python
            flow = OAuthFlow(region="us")
            token = flow.get_valid_token(region="us")
            headers = {"Authorization": f"Bearer {token}"}
            ```
        """
        tokens = self._storage.load_tokens(region=region)
        if tokens is None:
            raise OAuthError(
                "No OAuth tokens found. Please log in first with `mp account login NAME`.",
                code="OAUTH_TOKEN_ERROR",
            )

        if not tokens.is_expired():
            return tokens.access_token.get_secret_value()

        # Token is expired — refresh it
        client_info = self._storage.load_client_info(region=region)
        if client_info is None:
            raise OAuthError(
                "No OAuth client info found for refresh. "
                "Please log in again with `mp account login NAME`.",
                code="OAUTH_REFRESH_ERROR",
            )

        new_tokens = self.refresh_tokens(tokens=tokens, client_id=client_info.client_id)
        self._storage.save_tokens(new_tokens, region=region)
        return new_tokens.access_token.get_secret_value()

    def login(self, *, persist: bool = False, open_browser: bool = True) -> OAuthTokens:
        """Execute the full interactive OAuth PKCE login flow.

        Performs the following steps:
        1. Register (or load cached) OAuth client via DCR
        2. Generate PKCE challenge
        3. Start local callback server
        4. Open browser to Mixpanel authorization URL (or print URL when
           ``open_browser=False``)
        5. Wait for callback with authorization code
        6. Exchange code for tokens
        7. Save tokens to local storage (when ``persist`` is True)

        Args:
            persist: When True, the resulting :class:`OAuthTokens` are
                written to the configured :class:`OAuthStorage` at
                ``~/.mp/oauth/tokens_{region}.json`` (legacy v2 layout).
                Defaults to ``False`` because the v3 caller
                (``mp.accounts.login``) writes to the per-account
                ``~/.mp/accounts/{name}/tokens.json`` path itself —
                there is no remaining v2 caller after the B1 cleanup.
            open_browser: When True (default), launch the system browser
                to the authorize URL. When False, print the URL to stderr
                so the user can copy it manually (headless / SSH / CI).
                The local callback server still listens for the redirect
                either way.

        Returns:
            The obtained OAuthTokens with access and optional refresh tokens.

        Raises:
            OAuthError: If any step of the flow fails (registration, browser,
                callback, token exchange).

        Example:
            ```python
            flow = OAuthFlow(region="us")
            tokens = flow.login()
            print(tokens.access_token.get_secret_value()[:8])
            ```
        """
        # Step 1: Generate PKCE challenge and state
        pkce = PkceChallenge.generate()
        state = secrets.token_urlsafe(32)

        # Step 2: Find an available callback port by probing before binding
        bound_port = _find_available_port()
        if bound_port is None:
            raise OAuthError(
                f"All OAuth callback ports ({CALLBACK_PORTS}) are busy.",
                code="OAUTH_PORT_ERROR",
            )

        redirect_uri = f"http://localhost:{bound_port}/callback"

        # Step 3: Ensure client registration
        client_info = ensure_client_registered(
            http_client=self._http_client,
            region=self._region,
            redirect_uri=redirect_uri,
            storage=self._storage,
        )

        # Step 4: Build authorize URL and open browser
        authorize_url = self._build_authorize_url(
            client_id=client_info.client_id,
            redirect_uri=redirect_uri,
            challenge=pkce.challenge,
            state=state,
        )

        # Step 5: Set up two completers that race on a shared queue:
        #   1) The local callback server (always — handles same-machine case).
        #   2) Stdin paste reader (only when ``open_browser=False`` — handles
        #      "I opened the URL on my laptop, the localhost redirect failed,
        #      let me paste the URL back").
        # Whichever produces a valid (code, state) first wins. PKCE verifier
        # stays in this process so no on-disk persistence is needed.
        result_q: queue.Queue[CallbackResult] = queue.Queue(maxsize=1)
        error_q: queue.Queue[Exception] = queue.Queue(maxsize=1)

        def _run_callback() -> None:
            """Drive the local callback server; first completer wins."""
            try:
                result, _port = start_callback_server(
                    state=state, timeout=300.0, port=bound_port
                )
                with contextlib.suppress(queue.Full):
                    # Suppress: queue full means the other completer won.
                    result_q.put_nowait(result)
            except Exception as exc:
                with contextlib.suppress(queue.Full):
                    error_q.put_nowait(exc)

        def _run_paste_reader() -> None:
            """Read a pasted redirect URL / query string from stdin."""
            try:
                line = sys.stdin.readline()
                result = _parse_pasted_redirect(line, expected_state=state)
                with contextlib.suppress(queue.Full):
                    result_q.put_nowait(result)
            except Exception as exc:
                with contextlib.suppress(queue.Full):
                    error_q.put_nowait(exc)

        threading.Thread(target=_run_callback, daemon=True).start()
        if not open_browser:
            threading.Thread(target=_run_paste_reader, daemon=True).start()

        # Small delay to ensure callback server is listening before opening
        # browser / printing the URL.
        time.sleep(0.1)

        if open_browser:
            try:
                webbrowser.open(authorize_url)
            except Exception as exc:
                raise OAuthError(
                    f"Could not open browser for authorization: {exc}",
                    code="OAUTH_BROWSER_ERROR",
                    details={"authorize_url": authorize_url},
                ) from exc
        else:
            print(
                "Open this URL in your browser to authorize:\n"
                f"  {authorize_url}\n"
                "\n"
                "If the redirect to http://localhost:"
                f"{bound_port}/callback succeeds, the CLI will continue "
                "automatically.\n"
                "Otherwise, paste the redirect URL (or the `code=...&state=...` "
                "portion) below and press Enter:",
                file=sys.stderr,
                flush=True,
            )

        # Step 6: Wait for whichever completer produces first.
        try:
            callback_result = result_q.get(timeout=310.0)
        except queue.Empty as empty:
            try:
                err = error_q.get_nowait()
            except queue.Empty:
                raise OAuthError(
                    "Login timed out waiting for callback or paste.",
                    code="OAUTH_TIMEOUT",
                ) from empty
            if isinstance(err, OAuthError):
                raise err from None
            raise OAuthError(
                f"Callback / paste error: {err}",
                code="OAUTH_TOKEN_ERROR",
            ) from err

        # Step 7: Exchange code for tokens
        tokens = self.exchange_code(
            code=callback_result.code,
            verifier=pkce.verifier,
            client_id=client_info.client_id,
            redirect_uri=redirect_uri,
        )

        # Step 8: Save tokens (v2 layout) when the caller opts in.
        if persist:
            self._storage.save_tokens(tokens, region=self._region)

        return tokens

    def exchange_code(
        self,
        code: str,
        verifier: str,
        client_id: str,
        redirect_uri: str,
    ) -> OAuthTokens:
        """Exchange an authorization code for OAuth tokens.

        Sends a POST request to the token endpoint with the authorization
        code and PKCE verifier.

        Args:
            code: The authorization code from the callback.
            verifier: The PKCE code verifier.
            client_id: The registered OAuth client ID.
            redirect_uri: The redirect URI used in the authorization request.

        Returns:
            The obtained OAuthTokens.

        Raises:
            OAuthError: If the token exchange fails (``OAUTH_TOKEN_ERROR``).

        Example:
            ```python
            tokens = flow.exchange_code(
                code="auth-code",
                verifier="pkce-verifier",
                client_id="my-client",
                redirect_uri="http://localhost:19284/callback",
            )
            ```
        """
        form_data: dict[str, str] = {
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": redirect_uri,
            "client_id": client_id,
            "code_verifier": verifier,
        }
        return self._post_token_request(
            form_data,
            operation="Token exchange",
            error_code="OAUTH_TOKEN_ERROR",
        )

    def refresh_tokens(
        self,
        tokens: OAuthTokens,
        client_id: str,
        *,
        account_name: str | None = None,
    ) -> OAuthTokens:
        """Refresh OAuth tokens using a refresh token.

        Sends a POST request to the token endpoint with the refresh token
        to obtain new access and refresh tokens.

        Args:
            tokens: Current OAuthTokens containing the refresh token.
            client_id: The OAuth client ID.
            account_name: When supplied, embedded in OAuthError messages
                so the user knows exactly which account to recover (e.g.
                ``"Re-run `mp account login NAME`"``).

        Returns:
            New OAuthTokens with a fresh access token.

        Raises:
            OAuthError: If no refresh token is available
                (``OAUTH_REFRESH_ERROR``), the IdP rejects the refresh
                token as ``invalid_grant`` (``OAUTH_REFRESH_REVOKED`` —
                permanent, requires re-login), or the request fails for
                a transient reason (``OAUTH_REFRESH_ERROR``).

        Example:
            ```python
            new_tokens = flow.refresh_tokens(tokens, client_id="my-client")
            ```
        """
        if tokens.refresh_token is None:
            hint = (
                f"Run `mp account login {account_name}`."
                if account_name
                else "Run `mp account login NAME`."
            )
            raise OAuthError(
                f"Cannot refresh: no refresh token available. {hint}",
                code="OAUTH_REFRESH_ERROR",
                details=({"account_name": account_name} if account_name else {}),
            )

        form_data: dict[str, str] = {
            "grant_type": "refresh_token",
            "refresh_token": tokens.refresh_token.get_secret_value(),
            "client_id": client_id,
        }
        return self._post_token_request(
            form_data,
            operation="Token refresh",
            error_code="OAUTH_REFRESH_ERROR",
            account_name=account_name,
        )

    def _post_token_request(
        self,
        form_data: dict[str, str],
        *,
        operation: str,
        error_code: str,
        account_name: str | None = None,
    ) -> OAuthTokens:
        """POST form data to the token endpoint and parse the response.

        Shared implementation for both token exchange and token refresh
        requests, which follow the same request/response pattern.

        Args:
            form_data: Form-encoded body to POST.
            operation: Human-readable name for error messages
                (e.g., ``"Token exchange"`` or ``"Token refresh"``).
            error_code: OAuthError code to use on failure.
            account_name: When supplied, embedded in the actionable hint
                so the user knows exactly which account to re-login.

        Returns:
            Parsed OAuthTokens from the token endpoint response.

        Raises:
            OAuthError: If the request fails, returns a non-200 status,
                returns non-JSON, or is missing required fields. A 401
                response with ``error=invalid_grant`` is mapped to
                ``OAUTH_REFRESH_REVOKED`` so callers can give the user
                the precise "re-run login" recovery hint.

        Security:
            A 200 token-endpoint body may BE the live token payload even
            when it is malformed, so no 200-branch error path embeds it:

            - JSON-object body failing ``OAuthTokens.from_token_response``:
              ``details["response_data"]`` keeps every field name but only
              the primitive values of the safe RFC 6749 metadata keys
              (``token_type``, ``expires_in``, ``scope``, ``error``,
              ``error_description``); every other value — any key, any
              nesting — renders as ``"<redacted>"`` (ARB-B F-B2/E-1).
            - Non-object JSON body: fixed ``"<redacted non-object body>"``
              placeholder — the value itself can be the credential
              (ARB-B F-B3).
            - Body that fails JSON parsing (truncated / proxy-mangled
              token JSON): never embedded; only ``content_type`` and
              ``body_length`` (code points) survive (ARB-B F-B1).

            Non-200 branches still embed the raw ERROR body in
            ``details["response_body"]`` — those are IdP error documents
            (e.g. ``{"error": "invalid_grant"}``), not token grants, and
            their shapes are vector-locked. Fix-of-record:
            context/phase3/bug-reports/python-oauth-error-details-token-payload.md.
        """
        token_url = f"{self._base_url}token/"

        try:
            response = self._http_client.post(token_url, data=form_data)
        except httpx.HTTPError as exc:
            raise OAuthError(
                f"{operation} request failed: {exc}",
                code=error_code,
                details={"url": token_url},
            ) from exc

        if response.status_code != 200:
            # Distinguish a permanently dead refresh token (IdP returned
            # 400/401 with ``error=invalid_grant``) from a transient
            # network or 5xx failure. The dead-token case has a precise
            # recovery action; the transient case just wants a retry.
            invalid_grant = False
            if response.status_code in (400, 401):
                try:
                    payload = response.json()
                    invalid_grant = (
                        isinstance(payload, dict)
                        and payload.get("error") == "invalid_grant"
                    )
                except (json.JSONDecodeError, ValueError):
                    invalid_grant = False
            if invalid_grant and operation == "Token refresh":
                hint = (
                    f"Re-run `mp account login {account_name}`."
                    if account_name
                    else "Re-run `mp account login NAME`."
                )
                raise OAuthError(
                    (
                        f"Refresh token has been revoked or expired"
                        f"{f' for account {account_name!r}' if account_name else ''}"
                        f". {hint}"
                    ),
                    code="OAUTH_REFRESH_REVOKED",
                    details={
                        "status_code": response.status_code,
                        "response_body": response.text,
                        "account_name": account_name,
                    },
                )
            raise OAuthError(
                f"{operation} failed with status {response.status_code}: "
                f"{response.text}",
                code=error_code,
                details={
                    "status_code": response.status_code,
                    "response_body": response.text,
                    **({"account_name": account_name} if account_name else {}),
                },
            )

        try:
            data: dict[str, object] = response.json()
        except (json.JSONDecodeError, ValueError) as exc:
            # Never embed the body: a 200 that fails JSON parsing can still
            # BE the token payload (truncated JSON, trailing proxy garbage)
            # — ARB-B F-B1. body_length counts code points (the TS twin
            # uses Array.from(text).length for byte-identical vectors).
            raise OAuthError(
                f"{operation} returned non-JSON response: "
                f"{response.headers.get('content-type', 'unknown')}",
                code=error_code,
                details={
                    "content_type": response.headers.get("content-type", "unknown"),
                    "body_length": len(response.text),
                },
            ) from exc

        try:
            return OAuthTokens.from_token_response(data)
        except (KeyError, TypeError, ValueError) as exc:
            # Redact before embedding: `data` is a live (if malformed) token
            # payload — see the Security section of this docstring.
            # `response.json()` can yield any JSON value despite the dict
            # annotation; `_redact_token_payload` handles the non-dict edge
            # (ARB-A F1 guard, hardened to a placeholder by ARB-B F-B3) and
            # allowlist-redacts object bodies (ARB-B F-B2/E-1), mirroring
            # the TS twin's `redactTokenPayload` in oauth-http.ts.
            raise OAuthError(
                f"{operation} response missing required fields: {exc}",
                code=error_code,
                details={"response_data": _redact_token_payload(data)},
            ) from exc

    def _build_authorize_url(
        self,
        client_id: str,
        redirect_uri: str,
        challenge: str,
        state: str,
    ) -> str:
        """Build the OAuth authorization URL with PKCE parameters.

        Args:
            client_id: The registered OAuth client ID.
            redirect_uri: The callback redirect URI.
            challenge: The PKCE code challenge.
            state: The CSRF state parameter.

        Returns:
            The full authorization URL to open in the browser.
        """
        # scope intentionally omitted — DCR creates apps with an empty scope
        # field, so Django OAuth Toolkit defaults to ["__all__"], granting
        # every scope in OAUTH2_PROVIDER["SCOPES"] (~63 total).
        params: dict[str, str] = {
            "response_type": "code",
            "client_id": client_id,
            "redirect_uri": redirect_uri,
            "state": state,
            "code_challenge": challenge,
            "code_challenge_method": "S256",
        }
        return f"{self._base_url}authorize/?{urlencode(params)}"


def _find_available_port() -> int | None:
    """Probe CALLBACK_PORTS to find one that is not currently in use.

    Binds and immediately releases each candidate port on 127.0.0.1.
    Returns the first available port, or None if all are occupied.

    Returns:
        An available port number, or None.
    """
    for port in CALLBACK_PORTS:
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as test_sock:
                test_sock.bind(("127.0.0.1", port))
            return port
        except OSError:
            continue
    return None
