"""
mixpanel_headless - Python library for working with Mixpanel analytics data.

Complete programmable interface to Mixpanel analytics: discover your schema,
run live analytics, stream data, and manage entities via the App API.
"""

from mixpanel_headless import accounts, session, targets
from mixpanel_headless._internal.validation import validate_bookmark
from mixpanel_headless._literal_types import (
    CohortAggregationType,
    ConversionWindowUnit,
    CountType,
    CustomPropertyType,
    FilterDateUnit,
    FilterOperator,
    FilterPropertyType,
    FiltersCombinator,
    FlowAnchorType,
    FlowChartType,
    FlowConversionWindowUnit,
    FlowCountType,
    FlowNodeType,
    FlowSessionEvent,
    FrequencyFilterOperator,
    FunnelMathType,
    FunnelMode,
    FunnelOrder,
    FunnelReentryMode,
    HourDayUnit,
    InsightsMode,
    MathType,
    PerUserAggregation,
    QueryTimeUnit,
    RetentionAlignment,
    RetentionMathType,
    RetentionMode,
    RetentionUnboundedMode,
    SegmentMethod,
    TimeComparisonType,
    TimeComparisonUnit,
    TimeUnit,
)
from mixpanel_headless.accounts import login_unified
from mixpanel_headless.auth_types import (
    Account,
    AccountType,
    OAuthBrowserAccount,
    OAuthTokenAccount,
    Project,
    Region,
    ServiceAccount,
    Session,
    WorkspaceRef,
)
from mixpanel_headless.exceptions import (
    AccountExistsError,
    AccountInUseError,
    AccountNotFoundError,
    APIError,
    AuthenticationError,
    BookmarkValidationError,
    BusinessContextValidationError,
    ConfigError,
    DateRangeTooLargeError,
    EventNotFoundError,
    InvalidArgumentError,
    JQLSyntaxError,
    MixpanelHeadlessError,
    OAuthError,
    ProjectNotFoundError,
    QueryError,
    RateLimitError,
    RegionProbeError,
    RegionProbeNetworkError,
    ServerError,
    ValidationError,
    WorkspaceScopeError,
)
from mixpanel_headless.types import (
    # Business Context (AIE-147)
    BUSINESS_CONTEXT_MAX_CHARS,
    # Auth redesign (042) types
    AccountSummary,
    AccountTestResult,
    # Result types
    ActivityFeedResult,
    AlertBookmark,
    AlertCount,
    AlertCreator,
    AlertFrequencyPreset,
    AlertHistoryPagination,
    AlertHistoryResponse,
    AlertProject,
    AlertScreenshotResponse,
    AlertValidation,
    AlertWorkspace,
    # Operational Tooling types (Phase 026)
    Annotation,
    AnnotationTag,
    AnnotationUser,
    AuditResponse,
    AuditViolation,
    BlueprintCard,
    BlueprintConfig,
    BlueprintFinishParams,
    BlueprintTemplate,
    Bookmark,
    BookmarkHistoryPagination,
    BookmarkHistoryResponse,
    BookmarkInfo,
    BookmarkMetadata,
    BookmarkType,
    BulkAnomalyEntry,
    BulkCreateSchemasParams,
    BulkCreateSchemasResponse,
    # Data Governance types (Phase 027)
    BulkEventUpdate,
    BulkPatchResult,
    BulkPropertyUpdate,
    BulkUpdateAnomalyParams,
    BulkUpdateBookmarkEntry,
    BulkUpdateCohortEntry,
    BulkUpdateEventsParams,
    BulkUpdatePropertiesParams,
    BusinessContext,
    BusinessContextChain,
    Cohort,
    CohortBreakdown,
    CohortCreator,
    CohortCriteria,
    CohortDefinition,
    CohortInfo,
    CohortMetric,
    ComposedPropertyValue,
    CreateAlertParams,
    CreateAnnotationParams,
    CreateAnnotationTagParams,
    CreateBookmarkParams,
    CreateCohortParams,
    CreateCustomEventParams,
    CreateCustomPropertyParams,
    CreateDashboardParams,
    CreateDeletionRequestParams,
    CreateDropFilterParams,
    CreateExperimentParams,
    CreateFeatureFlagParams,
    CreateRcaDashboardParams,
    CreateTagParams,
    CreateWebhookParams,
    CursorPagination,
    CustomAlert,
    CustomEvent,
    CustomEventAlternative,
    CustomProperty,
    CustomPropertyRef,
    CustomPropertyResourceType,
    DailyCount,
    DailyCountsResult,
    Dashboard,
    DashboardRow,
    DashboardRowContent,
    DataVolumeAnomaly,
    DeleteSchemasResponse,
    DropFilter,
    DropFilterLimitsResponse,
    DuplicateExperimentParams,
    EngagementBucket,
    EngagementDistributionResult,
    EntityType,
    EventCountsResult,
    EventDefinition,
    EventDeletionRequest,
    Exclusion,
    Experiment,
    ExperimentConcludeParams,
    ExperimentCreator,
    ExperimentDecideParams,
    ExperimentStatus,
    FeatureFlag,
    FeatureFlagStatus,
    Filter,
    FlagContractStatus,
    FlagHistoryParams,
    FlagHistoryResponse,
    FlagLimitsResponse,
    # Result structure TypedDicts (Phase 038)
    FlowEdge,
    FlowQueryResult,
    FlowsResult,
    FlowStep,
    FlowStepNode,
    FlowTreeNode,
    Formula,
    FrequencyBreakdown,
    FrequencyFilter,
    FrequencyResult,
    FunnelInfo,
    FunnelQueryResult,
    FunnelResult,
    FunnelResultStep,
    FunnelStep,
    FunnelStepData,
    GroupBy,
    HoldingConstant,
    InitSchemaEnforcementParams,
    InlineCustomProperty,
    JQLResult,
    LexiconDefinition,
    LexiconMetadata,
    LexiconProperty,
    LexiconSchema,
    LexiconTag,
    ListItemGroupMode,
    LookupTable,
    LookupTableUploadUrl,
    MarkLookupTableReadyParams,
    Metric,
    NumericAverageResult,
    NumericBucketResult,
    NumericPropertySummaryResult,
    NumericSumResult,
    OAuthLoginResult,
    PaginatedResponse,
    PreviewDeletionFiltersParams,
    ProfilePageResult,
    ProjectWebhook,
    PropertyCountsResult,
    PropertyCoverage,
    PropertyCoverageResult,
    PropertyDefinition,
    PropertyDistributionResult,
    PropertyInput,
    PropertyResourceType,
    PropertySpec,
    PropertyValueCount,
    PublicWorkspace,
    QueryMeta,
    QueryResult,
    RcaSourceData,
    ReplaceSchemaEnforcementParams,
    RetentionCohortData,
    RetentionEvent,
    RetentionQueryResult,
    RetentionResult,
    SavedCohort,
    SavedReportResult,
    SavedReportType,
    SchemaEnforcementConfig,
    SchemaEntry,
    SegmentationResult,
    ServingMethod,
    SetTestUsersParams,
    SubPropertyInfo,
    Target,
    TimeComparison,
    TopEvent,
    UpdateAlertParams,
    UpdateAnnotationParams,
    UpdateAnomalyParams,
    UpdateBookmarkParams,
    UpdateCohortParams,
    UpdateCustomPropertyParams,
    UpdateDashboardParams,
    UpdateDropFilterParams,
    UpdateEventDefinitionParams,
    UpdateExperimentParams,
    UpdateFeatureFlagParams,
    UpdateLookupTableParams,
    UpdatePropertyDefinitionParams,
    UpdateReportLinkParams,
    UpdateSchemaEnforcementParams,
    UpdateTagParams,
    UpdateTextCardParams,
    UpdateWebhookParams,
    UploadLookupTableParams,
    UserEvent,
    UserQueryResult,
    ValidateAlertsForBookmarkParams,
    ValidateAlertsForBookmarkResponse,
    WebhookAuthType,
    WebhookMutationResult,
    WebhookTestParams,
    WebhookTestResult,
)
from mixpanel_headless.workspace import Workspace

__version__ = "0.1.1"

__all__ = [
    # Core
    "Workspace",
    # Auth redesign (042) types
    "Account",
    "AccountType",
    "OAuthBrowserAccount",
    "OAuthTokenAccount",
    "Region",
    "ServiceAccount",
    "Project",
    "Session",
    "WorkspaceRef",
    "AccountSummary",
    "AccountTestResult",
    "OAuthLoginResult",
    "Target",
    # Auth redesign (042) namespaces
    "accounts",
    "session",
    "targets",
    # 043 frictionless-auth orchestrator
    "login_unified",
    # Auth redesign (042) exceptions
    "AccountInUseError",
    # Validation
    "validate_bookmark",
    # Type aliases — time units
    "TimeUnit",
    "HourDayUnit",
    "QueryTimeUnit",
    # Type aliases — count/math types
    "CountType",
    "MathType",
    "PerUserAggregation",
    # Type aliases — funnel types
    "FunnelMathType",
    "ConversionWindowUnit",
    "FunnelOrder",
    "FunnelMode",
    # Type aliases — retention types
    "RetentionAlignment",
    "RetentionMode",
    "RetentionMathType",
    # Type aliases — flow types
    "FlowCountType",
    "FlowChartType",
    "FlowConversionWindowUnit",
    "FlowNodeType",
    "FlowAnchorType",
    # Type aliases — insights
    "InsightsMode",
    # Type aliases — filter types
    "CustomPropertyType",
    "FilterOperator",
    "FilterPropertyType",
    "FilterDateUnit",
    "FiltersCombinator",
    # Type aliases — advanced query types
    "SegmentMethod",
    "FunnelReentryMode",
    "RetentionUnboundedMode",
    "TimeComparisonType",
    "TimeComparisonUnit",
    "CohortAggregationType",
    "FlowSessionEvent",
    "FrequencyFilterOperator",
    # Result structure TypedDicts
    "QueryMeta",
    "FunnelStepData",
    "RetentionCohortData",
    "FlowStepNode",
    "FlowEdge",
    # Exceptions
    "MixpanelHeadlessError",
    "BookmarkValidationError",
    "ValidationError",
    "APIError",
    "ConfigError",
    "InvalidArgumentError",
    "AccountNotFoundError",
    "AccountExistsError",
    "ProjectNotFoundError",
    "AuthenticationError",
    "RateLimitError",
    "QueryError",
    "JQLSyntaxError",
    "ServerError",
    "EventNotFoundError",
    "DateRangeTooLargeError",
    "OAuthError",
    "RegionProbeError",
    "RegionProbeNetworkError",
    "WorkspaceScopeError",
    "BusinessContextValidationError",
    # Result types
    "SegmentationResult",
    "FunnelResult",
    "FunnelResultStep",
    "RetentionResult",
    "CohortInfo",
    "JQLResult",
    # Discovery types
    "FunnelInfo",
    "SavedCohort",
    "SubPropertyInfo",
    "TopEvent",
    "EventCountsResult",
    "PropertyCountsResult",
    # Bookmark types (Phase 015)
    "BookmarkInfo",
    "BookmarkType",
    "SavedReportResult",
    "SavedReportType",
    "FlowsResult",
    # Phase 008: Query Service Enhancement types
    "UserEvent",
    "ActivityFeedResult",
    "FrequencyResult",
    "NumericBucketResult",
    "NumericSumResult",
    "NumericAverageResult",
    # Lexicon schema types
    "EntityType",
    "LexiconMetadata",
    "LexiconProperty",
    "LexiconDefinition",
    "LexiconSchema",
    # JQL Discovery types (Phase 016)
    "PropertyDistributionResult",
    "PropertyValueCount",
    "NumericPropertySummaryResult",
    "DailyCountsResult",
    "DailyCount",
    "EngagementDistributionResult",
    "EngagementBucket",
    "PropertyCoverageResult",
    "PropertyCoverage",
    # Profile pagination
    "ProfilePageResult",
    # App API types (Phase 023)
    "PublicWorkspace",
    "CursorPagination",
    "PaginatedResponse",
    # Core Entity CRUD types (Phase 024)
    "Dashboard",
    "CreateDashboardParams",
    "DashboardRow",
    "DashboardRowContent",
    "UpdateDashboardParams",
    "BlueprintTemplate",
    "BlueprintConfig",
    "BlueprintCard",
    "BlueprintFinishParams",
    "CreateRcaDashboardParams",
    "RcaSourceData",
    "UpdateReportLinkParams",
    "UpdateTextCardParams",
    "Bookmark",
    "BookmarkMetadata",
    "CreateBookmarkParams",
    "UpdateBookmarkParams",
    "BulkUpdateBookmarkEntry",
    "BookmarkHistoryResponse",
    "BookmarkHistoryPagination",
    # Cohort Definition Builder (Phase 035)
    "CohortCriteria",
    "CohortDefinition",
    # Cohort Behaviors (Phase 036)
    "CohortBreakdown",
    "CohortMetric",
    # Custom Property Query Types (Phase 037)
    "PropertyInput",
    "InlineCustomProperty",
    "CustomPropertyRef",
    "PropertySpec",
    # Cohort CRUD (Phase 024)
    "Cohort",
    "CohortCreator",
    "CreateCohortParams",
    "UpdateCohortParams",
    "BulkUpdateCohortEntry",
    # Feature Management types (Phase 025)
    "FeatureFlagStatus",
    "ServingMethod",
    "FlagContractStatus",
    "ExperimentStatus",
    "ExperimentCreator",
    "FeatureFlag",
    "CreateFeatureFlagParams",
    "UpdateFeatureFlagParams",
    "SetTestUsersParams",
    "FlagHistoryParams",
    "FlagHistoryResponse",
    "FlagLimitsResponse",
    "Experiment",
    "CreateExperimentParams",
    "UpdateExperimentParams",
    "ExperimentConcludeParams",
    "ExperimentDecideParams",
    "DuplicateExperimentParams",
    # Operational Tooling types (Phase 026)
    "Annotation",
    "AnnotationUser",
    "AnnotationTag",
    "CreateAnnotationParams",
    "UpdateAnnotationParams",
    "CreateAnnotationTagParams",
    "ProjectWebhook",
    "WebhookAuthType",
    "CreateWebhookParams",
    "UpdateWebhookParams",
    "WebhookTestParams",
    "WebhookTestResult",
    "WebhookMutationResult",
    "CustomAlert",
    "AlertBookmark",
    "AlertCreator",
    "AlertWorkspace",
    "AlertProject",
    "AlertFrequencyPreset",
    "CreateAlertParams",
    "UpdateAlertParams",
    "AlertCount",
    "AlertHistoryResponse",
    "AlertHistoryPagination",
    "AlertScreenshotResponse",
    "AlertValidation",
    "ValidateAlertsForBookmarkParams",
    "ValidateAlertsForBookmarkResponse",
    # Data Governance types (Phase 027)
    "PropertyResourceType",
    "CustomPropertyResourceType",
    "EventDefinition",
    "PropertyDefinition",
    "UpdateEventDefinitionParams",
    "UpdatePropertyDefinitionParams",
    "BulkEventUpdate",
    "BulkUpdateEventsParams",
    "BulkPropertyUpdate",
    "BulkUpdatePropertiesParams",
    "LexiconTag",
    "CreateTagParams",
    "UpdateTagParams",
    "DropFilter",
    "CreateDropFilterParams",
    "UpdateDropFilterParams",
    "DropFilterLimitsResponse",
    "ComposedPropertyValue",
    "CustomProperty",
    "CreateCustomPropertyParams",
    "UpdateCustomPropertyParams",
    "LookupTable",
    "UploadLookupTableParams",
    "MarkLookupTableReadyParams",
    "LookupTableUploadUrl",
    "UpdateLookupTableParams",
    "CustomEvent",
    "CustomEventAlternative",
    "CreateCustomEventParams",
    # Business Context (AIE-147)
    "BUSINESS_CONTEXT_MAX_CHARS",
    "BusinessContext",
    "BusinessContextChain",
    # Query API types (Phase 029)
    "MathType",
    "PerUserAggregation",
    "Metric",
    "Filter",
    "Formula",
    "GroupBy",
    "ListItemGroupMode",
    "CustomPropertyType",
    "FilterDateUnit",
    "FilterOperator",
    "FilterPropertyType",
    "QueryResult",
    # Schema Registry & Data Governance types (Phase 028)
    "SchemaEntry",
    "BulkCreateSchemasParams",
    "BulkCreateSchemasResponse",
    "BulkPatchResult",
    "DeleteSchemasResponse",
    "SchemaEnforcementConfig",
    "InitSchemaEnforcementParams",
    "UpdateSchemaEnforcementParams",
    "ReplaceSchemaEnforcementParams",
    "AuditResponse",
    "AuditViolation",
    "DataVolumeAnomaly",
    "UpdateAnomalyParams",
    "BulkUpdateAnomalyParams",
    "BulkAnomalyEntry",
    "EventDeletionRequest",
    "CreateDeletionRequestParams",
    "PreviewDeletionFiltersParams",
    # Funnel Query types (Phase 032)
    "FunnelStep",
    "Exclusion",
    "HoldingConstant",
    "FunnelMathType",
    "FunnelQueryResult",
    # Retention Query types (Phase 033)
    "RetentionAlignment",
    "RetentionEvent",
    "RetentionMathType",
    "RetentionMode",
    "RetentionQueryResult",
    # Flow Query types (Phase 034)
    "FlowStep",
    "FlowTreeNode",
    "FlowQueryResult",
    # User query types (Phase 039)
    "UserQueryResult",
    "TimeComparison",
    "FrequencyBreakdown",
    "FrequencyFilter",
]
